const gulp = require('gulp');
const revDistClean = require('gulp-rev-dist-clean');

const fs = require('fs');

const config = require('../config');

// Revision clean
const revisionClean = function(done) {
	if (fs.existsSync(config.build.manifest)) {
		return gulp.src([
				config.build.root + '/**/*.css',
				config.build.root + '/**/*.svg',
				config.build.rootException + '/img/**/*.svg'
			], {read: false})
			.pipe(revDistClean(config.build.manifest, { // Delete old files
				keepRenamedFiles: true, // Keep the original files generated by gulp-rev?
				keepOriginalFiles: true // Keep the original revised files?
			}))
			.on('end', done);
	} else {
		console.log('Revision clean error, file not exist.');
		done();
		return false;
	}
}

module.exports = revisionClean;
