name: Update boilerplate elements

on:
  push:
    branches:
      - master

jobs:
  updateBoilerplateElements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: alkorlos/boilerplate-elements
          token: ${{ secrets.UpdateBoilerplatesKey }}

      - name: Git
        run: |
          git remote add upstream https://github.com/alkorlos/bundler.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
